// Code generated by "spawner "; DO NOT EDIT.

package main

import "sync"

var spawnerPools = map[string]*sync.Pool{
	"main.val":  {New: func() interface{} { return spawner["main.val"] }},
	"main.Dal2": {New: func() interface{} { return spawner["main.Dal2"] }},
	"main.st":   {New: func() interface{} { return spawner["main.st"] }},
}
