// Code generated by "spawner "; DO NOT EDIT.

package main

type factory func() interface{}

func Spawner(name string, newPool ...bool) (interface{}, bool) {
	f, ok := spawner[name]
	if !ok {
		return nil, ok
	}
	return f(), true
}

var spawner = map[string]factory{
	"main.st":   func() interface{} { return &st{} },
	"main.val":  func() interface{} { return &val{} },
	"main.Dal2": func() interface{} { return &Dal2{} },
}

func Put(name string, x interface{}) {}
